version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: gator
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ../sql/schema:/docker-entrypoint-initdb.d:ro
